version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=airline_db'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080
